name: androidBuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Restore Previous Cache
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install hxcpp-debug-server
          haxelib install lime 7.9.0
          haxelib install openfl 9.2.0
          haxelib install flixel 5.5.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson 1.4.0
          haxelib install hxCodec 2.6.0
          haxelib install SScript 8.1.6
          haxelib install hscript 2.5.0
          haxelib install hxCodec 2.6.0
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc
          haxelib git flxanimate https://github.com/beihu235/flxanimate
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation
          haxelib list         

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -${{ matrix.arch }}
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
        
